In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"G:\Analysys\data\covid_vaccine_statewise.csv")
df.shape

(7845, 24)

In [10]:
result = []
for k,v in df.iterrows():
    result.append(v)
df.columns

Index(['Updated On', 'State', 'Total Doses Administered', 'Sessions',
       ' Sites ', 'First Dose Administered', 'Second Dose Administered',
       'Male (Doses Administered)', 'Female (Doses Administered)',
       'Transgender (Doses Administered)', ' Covaxin (Doses Administered)',
       'CoviShield (Doses Administered)', 'Sputnik V (Doses Administered)',
       'AEFI', '18-44 Years (Doses Administered)',
       '45-60 Years (Doses Administered)', '60+ Years (Doses Administered)',
       '18-44 Years(Individuals Vaccinated)',
       '45-60 Years(Individuals Vaccinated)',
       '60+ Years(Individuals Vaccinated)', 'Male(Individuals Vaccinated)',
       'Female(Individuals Vaccinated)', 'Transgender(Individuals Vaccinated)',
       'Total Individuals Vaccinated'],
      dtype='object')

In [ ]:
✔ What is Pandas?

A Python library for data manipulation + analysis.
Built on NumPy.

In [ ]:
✔ Main Data Structures

Series → 1D

DataFrame → 2D tabular data

In [17]:
s1 = pd.Series(["umesh","Ramesh"])
s2 = pd.Series([10,20,30])
s3 = pd.Series([10,20,30])

In [14]:
df = pd.DataFrame({"Name" : s1,"Age": s2})

In [15]:
df

     Name  Age
0   umesh   10
1  Ramesh   20
2     NaN   30

In [22]:
df1 = pd.DataFrame({"Name" : s2,"Age": s3})
df1

   Name  Age
0    10   10
1    20   20
2    30   30

In [21]:
df1.sum(axis=0)

Name    60
Age     60
dtype: int64

In [23]:
df1.sum(axis=1)

0    20
1    40
2    60
dtype: int64

In [ ]:
pd.read_csv("file.csv")
pd.read_excel("file.xlsx")
pd.read_json("file.json")

In [ ]:
# ✔ Write data
df.to_csv("out.csv", index=False)

In [ ]:
# 🔹 3. DataFrame Operations
df.head()
df.tail()
df.info()
df.describe()

In [ ]:
✔ Select columns
df['col']
df[['col1', 'col2']]

In [ ]:
✔ Select rows
df.loc[0]     # label
df.iloc[0]    # index position
df.loc[2:5]
df.iloc[3:8]

In [ ]:
✔ Add / Remove columns
df['new'] = df['A'] + 10
df.drop('col1',axis=1)

In [ ]:
✔ Rename
df.rename(columns={'old': 'new'})

In [ ]:
# 🔹 4. Filtering & Conditional Operations
df[df['age'] > 30]

In [ ]:
# ✔ Multiple conditions
df[(df['age'] > 30) & (df['city'] == 'Delhi')]

In [ ]:
✔ isin
df[df['city'].isin(['Delhi', 'Mumbai'])]

In [ ]:
# Between
df[df['salary'].between(30000, 50000)]

In [ ]:
🔹 5. Handling Missing Data (Very Important in Interviews)
# ✔ Find null values
df.isna()
df.isna().sum()

In [25]:
# ✔ Drop missing
df.dropna()

   Name  Age
0    10   10
1    20   20
2    30   30

In [28]:
# ✔ Fill missing
df.fillna(0)
df.fillna(df['Age'].mean())

   Name  Age
0    10   10
1    20   20
2    30   30

In [ ]:
# ✔ Replace
df.replace("?", None)

In [ ]:
df.sort_values('salary')
df.sort_values(['dept', 'salary'], ascending=[True, False])

In [ ]:
# Rank values
df['rank'] = df['score'].rank(ascending=False)

In [ ]:
# GroupBy
df.groupby('department')['salary'].sum()

In [ ]:
✔ Multiple aggregations
df.groupby('department').agg({
    'salary': ['sum', 'mean', 'max'],
    'age': 'mean'
})

In [29]:
import pandas as pd

data = {
    'department': ['HR', 'HR', 'IT', 'IT', 'Sales', 'Sales'],
    'salary': [30000, 35000, 50000, 55000, 45000, 47000],
    'age': [25, 28, 30, 32, 27, 29]
}

df = pd.DataFrame(data)
print(df)

  department  salary  age
0         HR   30000   25
1         HR   35000   28
2         IT   50000   30
3         IT   55000   32
4      Sales   45000   27
5      Sales   47000   29

In [30]:
result = df.groupby('department').agg({
    'salary': ['sum', 'mean', 'max'],
    'age': 'mean'
})

print(result)

            salary                   age
               sum     mean    max  mean
department
HR           65000  32500.0  35000  26.5
IT          105000  52500.0  55000  31.0
Sales        92000  46000.0  47000  28.0

In [31]:
# ✔ transform (very important)
import pandas as pd

df = pd.DataFrame({
    'department': ['HR', 'HR', 'IT', 'IT', 'Sales', 'Sales'],
    'salary': [30000, 35000, 50000, 55000, 45000, 47000]
})

print(df)

  department  salary
0         HR   30000
1         HR   35000
2         IT   50000
3         IT   55000
4      Sales   45000
5      Sales   47000

In [32]:
#✅ Apply transform()
df['dept_avg'] = df.groupby('department')['salary'].transform('mean')

In [33]:
df

  department  salary  dept_avg
0         HR   30000   32500.0
1         HR   35000   32500.0
2         IT   50000   52500.0
3         IT   55000   52500.0
4      Sales   45000   46000.0
5      Sales   47000   46000.0

In [ ]:
🔹 8. Merging, Joining & Concatenation (Interview Favorite)

In [ ]:
pd.concat([df1, df2], axis=0)
pd.concat([df1, df2], axis=1)

In [ ]:
# ✔ merge (SQL JOINs)
pd.merge(df1, df2, on='id', how='inner')
pd.merge(df1, df2, how='left')
pd.merge(df1, df2, how='outer')

In [ ]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

In [ ]:
✔ 1. Top 3 employees with highest salary in each department

df = df.sort_values('salary',ascending=False).groupby('department').head(3)

In [8]:
import pandas as pd

data = {
    'employee': ['A','B','C','D','E','F','G','H','I'],
    'department': ['IT','IT','IT','HR','HR','Finance','Finance','Finance','Finance'],
    'salary': [90000, 85000, 78000, 60000, 65000, 70000, 72000, 68000, 75000]
}

df = pd.DataFrame(data)
print(df)

  employee department  salary
0        A         IT   90000
1        B         IT   85000
2        C         IT   78000
3        D         HR   60000
4        E         HR   65000
5        F    Finance   70000
6        G    Finance   72000
7        H    Finance   68000
8        I    Finance   75000

In [9]:
df = df.sort_values('salary').groupby('department')
df

In [4]:
df = df.sort_values('salary').groupby('department').head(1)

In [5]:
df

  employee department  salary
3        D         HR   60000
7        H    Finance   68000
2        C         IT   78000

In [ ]:
✔ 2. Find employees with salary greater than department average
df['avg'] = df.groupby('department')['salary'].transform('mean')
df[df['salary'] > df['avg']]

In [ ]:
# ✔ 3. Count missing values column-wise
df.isna().sum()

In [ ]:
You have 40% missing data in some columns. How do you handle this?

  1️⃣ Understand the Missingness Type
     Before deciding anything
  2️⃣ Analyze Feature Importance
  3️⃣ Choose the Right Strategy Based on Column Type

        A. Numerical Column (40% NA)
               Mean/Median (if data is normally distributed or skewed)
        B. Categorical Column (40% NA)
            Option 1 — Fill with Mode
            df['col'].fillna(df['col'].mode()[0], inplace=True)
4️⃣ Drop Column Only if Necessary

In [ ]:
“If a column has 40% missing data, I don’t blindly drop it.
I first analyze why the data is missing (MCAR, MAR, MNAR).
If the feature is important, I try advanced imputation like
KNN or MICE for numerical variables, or mode/‘Unknown’ imputation for categorical variables.
I also create a missingness indicator because missing values often carry useful signals.
I drop the column only if it has low importance or cannot be reliably imputed.
Finally, I compare model performance before and after imputation.