In [1]:
import pandas as pd
stocks = ['AMZN', 'CACC', 'EQIX', 'GOOG', 'ORLY', 'ULTA']

prices = [
    [12.81, 11.09, 12.11, 10.93, 9.83, 8.14],
    [10.34, 10.56, 10.14, 12.17, 13.1, 11.22],
    [11.53, 10.67, 10.42, 11.88, 11.77, 10.21]
]

In [32]:
new_df = pd.DataFrame(prices,columns= stocks)

In [33]:
new_df

    AMZN   CACC   EQIX   GOOG   ORLY   ULTA
0  12.81  11.09  12.11  10.93   9.83   8.14
1  10.34  10.56  10.14  12.17  13.10  11.22
2  11.53  10.67  10.42  11.88  11.77  10.21

In [34]:
new_df_1 = new_df.sum(axis=0)

In [28]:
df1

AMZN    34.68
CACC    32.32
EQIX    32.67
GOOG    34.98
ORLY    34.70
ULTA    29.57
dtype: float64

In [31]:
df1

AMZN    34.68
CACC    32.32
EQIX    32.67
GOOG    34.98
ORLY    34.70
ULTA    29.57
dtype: float64

In [36]:
df

    AMZN   CACC   EQIX   GOOG   ORLY   ULTA
0  12.81  11.09  12.11  10.93   9.83   8.14
1  10.34  10.56  10.14  12.17  13.10  11.22
2  11.53  10.67  10.42  11.88  11.77  10.21

In [35]:
top3_stock_avg = df.mean().sort_values(ascending=False).head(3)
print(top3_stock_avg)

GOOG    11.660000
ORLY    11.566667
AMZN    11.560000
dtype: float64