In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    
      "Num1" : [1,2,3],
      "Num2"  : [4,5,6]
    
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Num1  Num2
0     1     4
1     2     5
2     3     6

In [6]:
df.sum(axis=0)

Num1     6
Num2    15
dtype: int64

In [2]:
import pandas as pd

data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math':   [85, 90, 75, 80],
    'Science': [88, 85, 90, 82],
    'English': [82, 88, 85, 90]
}

df = pd.DataFrame(data)
print(df)

   Student  Math  Science  English
0    Alice    85       88       82
1      Bob    90       85       88
2  Charlie    75       90       85
3    David    80       82       90

In [3]:
col_avg = df[['Math', 'Science', 'English']].mean(axis=0)
print(col_avg)

Math       82.50
Science    86.25
English    86.25
dtype: float64

In [4]:
df["Row_Avg"] = df[['Math', 'Science', 'English']].mean(axis=1)
print(df)

   Student  Math  Science  English    Row_Avg
0    Alice    85       88       82  85.000000
1      Bob    90       85       88  87.666667
2  Charlie    75       90       85  83.333333
3    David    80       82       90  84.000000

In [10]:
import pandas as pd

# Step 1: Create DataFrame
data = [
    [1, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [2, 'SS', 12, 1234, '10/12/2022', 'HYD'],
    [3, 'SS', 12, 1234, '10/12/2022', 'DEL'],
    [4, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [5, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [6, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [7, 'SS', 12, 1234, '10/12/2022', 'HYD'],
    [8, 'SS', 12, 1234, '10/12/2022', 'PUN']
]

df = pd.DataFrame(
    data,
    columns=['ID', 'TYPE', 'NUM1', 'NUM2', 'DATE', 'CITY']
)

In [2]:
df

   ID TYPE  NUM1  NUM2        DATE CITY
0   1   SS    12  1234  10/12/2022  BLR
1   2   SS    12  1234  10/12/2022  HYD
2   3   SS    12  1234  10/12/2022  DEL
3   4   SS    12  1234  10/12/2022  BLR
4   5   SS    12  1234  10/12/2022  BLR
5   6   SS    12  1234  10/12/2022  BLR
6   7   SS    12  1234  10/12/2022  HYD
7   8   SS    12  1234  10/12/2022  PUN

In [3]:
blr_idx = df.index[df['CITY'] == 'BLR']

In [4]:
blr_idx

Index([0, 3, 4, 5], dtype='int64')

In [8]:
#  df.iloc[1, 5] = "dd"

In [13]:
df.iloc[0,2]

np.int64(12)

In [14]:
df.loc[[1, 3]]

   ID TYPE  NUM1  NUM2        DATE CITY
1   2   SS    12  1234  10/12/2022  HYD
3   4   SS    12  1234  10/12/2022  BLR

In [15]:
df.iloc[[1, 3]]

   ID TYPE  NUM1  NUM2        DATE CITY
1   2   SS    12  1234  10/12/2022  HYD
3   4   SS    12  1234  10/12/2022  BLR

In [18]:
df.iloc[1,5]

'HYD'

In [19]:
df.loc[1:3]

   ID TYPE  NUM1  NUM2        DATE CITY
1   2   SS    12  1234  10/12/2022  HYD
2   3   SS    12  1234  10/12/2022  DEL
3   4   SS    12  1234  10/12/2022  BLR

In [27]:
df.iloc[1:3,2:4]

   NUM1  NUM2
1    12  1234
2    12  1234

In [28]:
import pandas as pd

# Step 1: Create DataFrame
data = [
    [1, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [2, 'SS', 12, 1234, '10/12/2022', 'HYD'],
    [3, 'SS', 12, 1234, '10/12/2022', 'DEL'],
    [4, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [5, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [6, 'SS', 12, 1234, '10/12/2022', 'BLR'],
    [7, 'SS', 12, 1234, '10/12/2022', 'HYD'],
    [8, 'SS', 12, 1234, '10/12/2022', 'PUN']
]

df = pd.DataFrame(
    data,
    columns=['ID', 'TYPE', 'NUM1', 'NUM2', 'DATE', 'CITY']
)

In [29]:
blr_idx = df.index[df['CITY'] == 'BLR']

In [30]:
blr_idx

Index([0, 3, 4, 5], dtype='int64')

In [31]:
blr_idx[:2]

Index([0, 3], dtype='int64')

In [35]:
df.loc[[4,5], 'CITY'] = 'PUN'

In [36]:
df

   ID TYPE  NUM1  NUM2        DATE CITY
0   1   SS    12  1234  10/12/2022  PUN
1   2   SS    12  1234  10/12/2022  HYD
2   3   SS    12  1234  10/12/2022  DEL
3   4   SS    12  1234  10/12/2022  PUN
4   5   SS    12  1234  10/12/2022  PUN
5   6   SS    12  1234  10/12/2022  PUN
6   7   SS    12  1234  10/12/2022  HYD
7   8   SS    12  1234  10/12/2022  PUN