In [5]:
import pandas as pd

df = pd.DataFrame({
    'ID': [1, 2, 2, 3, 3],
    'CITY': ['BLR', 'HYD', 'HYD', 'DEL', 'DEL'],
    'SALARY': [50000, 60001, 60000, 55000, 55000]
})

print(df)

   ID CITY  SALARY
0   1  BLR   50000
1   2  HYD   60001
2   2  HYD   60000
3   3  DEL   55000
4   3  DEL   55000

In [6]:
df = df.drop_duplicates()

In [7]:
df

   ID CITY  SALARY
0   1  BLR   50000
1   2  HYD   60001
2   2  HYD   60000
3   3  DEL   55000

In [ ]:
🔹 2. Remove duplicates based on one column
df_city = df.drop_duplicates(subset=['CITY'])
print(df_city)

In [ ]:
| Feature             | merge | join       | concat |
| ------------------- | ----- | ---------- | ------ |
| Similar to SQL JOIN | ✅     | ✅          | ❌      |
| Join on column      | ✅     | ⚠️ Limited | ❌      |
| Join on index       | ⚠️    | ✅          | ❌      |
| Stack DataFrames    | ❌     | ❌          | ✅      |
| Requires key        | ✅     | Usually    | ❌      |

merge() → join on columns

join() → join on index

In [8]:
import pandas as pd

df1 = pd.DataFrame({
    'EMP_ID': [1, 2, 3],
    'NAME': ['Amit', 'Neha', 'Rahul']
})

df2 = pd.DataFrame({
    'EMP_ID': [2, 3, 4],
    'SALARY': [60000, 70000, 80000]
})

In [9]:
df1

   EMP_ID   NAME
0       1   Amit
1       2   Neha
2       3  Rahul

In [10]:
df2

   EMP_ID  SALARY
0       2   60000
1       3   70000
2       4   80000

In [13]:
# Merge
pd.merge(df1, df2, on='EMP_ID', how='right')

   EMP_ID   NAME  SALARY
0       2   Neha   60000
1       3  Rahul   70000
2       4    NaN   80000

In [15]:
# 2️⃣ join() → Join using index (or key column)
df1_indexed = df1.set_index('EMP_ID')
df2_indexed = df2.set_index('EMP_ID')

In [16]:
df1_indexed.join(df2_indexed)

         NAME   SALARY
EMP_ID
1        Amit      NaN
2        Neha  60000.0
3       Rahul  70000.0

In [ ]:
🔹 Row-wise concat (default)
pd.concat([df1, df1])

In [ ]:
🔹 Column-wise concat
pd.concat([df1, df2], axis=1)