In [1]:
import pandas as pd

data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math':   [85, 90, 75, 80],
    'Science': [88, 85, 90, 82],
    'English': [82, 88, 85, 90]
}

df = pd.DataFrame(data)
print(df)

   Student  Math  Science  English
0    Alice    85       88       82
1      Bob    90       85       88
2  Charlie    75       90       85
3    David    80       82       90

In [2]:
df

   Student  Math  Science  English
0    Alice    85       88       82
1      Bob    90       85       88
2  Charlie    75       90       85
3    David    80       82       90

In [3]:
df[["Math","Science"]]

   Math  Science
0    85       88
1    90       85
2    75       90
3    80       82

In [4]:

# ---- Child-wise average ----
df['child_average'] = df[['Math', 'Science', 'English']].mean(axis=1)

In [5]:
df['child_average']

0    85.000000
1    87.666667
2    83.333333
3    84.000000
Name: child_average, dtype: float64

In [6]:
# ---- Subject-wise average ----
subject_average = df[['Math', 'Science', 'English']].sum()

print(subject_average)
top_subject = subject_average.sort_values(ascending=False).head(2)

Math       330
Science    345
English    345
dtype: int64

In [15]:
print(top_subject)

Science    345
English    345
dtype: int64

In [8]:
data = {"name" : ["umesh","ramesh"],
       "salary": [1000,2000],
       "id": [1,2]}

dept = {"eid" : [1,2],
       "dname" : ["HR","IT"]
       }

df = pd.DataFrame(data)
df1 = pd.DataFrame(dept)
df2 = df.join(df1)
df2

     name  salary  id  eid dname
0   umesh    1000   1    1    HR
1  ramesh    2000   2    2    IT

In [1]:
import pandas as pd

# Sample data
data1 = {
    "ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"]
}

data2 = {
    "ID": [5, 6],
    "Name": ["Eve", "Frank"]
}

# Create DataFrames
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Concatenate DataFrames along rows
concat_df = pd.concat([df1, df2], ignore_index=True)

print("Concatenated DataFrame (along rows):")
print(concat_df)

Concatenated DataFrame (along rows):
   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eve
5   6    Frank

In [ ]:
import pandas as pd

# Sample data
data_left = {
    "ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"]
}

data_right = {
    "Score": [85, 90, 88, 92]
}

# Create DataFrames
df_left = pd.DataFrame(data_left)
df_right = pd.DataFrame(data_right, index=[1, 2, 3, 4])

# Set index for the left DataFrame
df_left.set_index('ID', inplace=True)

# Perform join
joined_df = df_left.join(df_right)

print("Joined DataFrame (left join):")
print(joined_df)

In [ ]:
import pandas as pd

# Sample data
data_left = {
    "ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"]
}

# Create DataFrames
df_left = pd.DataFrame(data_left)

df_left.set_index('ID', inplace=True)

print(df_left)

In [11]:
import pandas as pd

# Sample data
data_left = {
    "ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"]
}

data_right = {
    "ID": [3, 4, 5, 6,7],
    "Score": [85, 90, 88, 92,44]
}

# Create DataFrames
df_left = pd.DataFrame(data_left)
df_right = pd.DataFrame(data_right)

# Perform merge (inner join by default)
merged_df = pd.merge(df_left, df_right, on="ID")

print("Merged DataFrame (inner join):")
print(merged_df)

Merged DataFrame (inner join):
   ID     Name  Score
0   3  Charlie     85
1   4    David     90

In [ ]:
data = {
    "Name" : [1,2,3,4,'umesh','samal']
}
data1 = {
    "Name1" : [1,2,3,4,'umesh','samal',8,9]
}
df = pd.DataFrame(data)
df1 = pd.DataFrame(data1)
name_set = set(df['Name'])
name1_set = set(df1['Name1'])
# Find the difference
difference = name1_set - name_set

# Convert the result to a list and sort (if needed)
output = list(difference)

# Print the output
print(output)

In [ ]:
| Feature       | `merge()`                        | `join()`               | `concat()`                           |
| ------------- | -------------------------------- | ---------------------- | ------------------------------------ |
| Purpose       | SQL-style joins                  | Index-based joins      | Stacking DataFrames                  |
| Join Type     | inner/left/right/outer           | inner/left/right/outer | vertical or horizontal concatenation |
| Works On      | Columns (or index)               | Index (or left column) | Rows or columns                      |
| Syntax Style  | SQL-like                         | Method of DataFrame    | Simple stacking                      |
| Key Required? | Yes                              | Usually index          | No                                   |
| Best Use Case | Combine tables using key columns | Combine by index       | Add rows or columns                  |