In [16]:
import pandas as pd

# Sample data
data = {
    'date': ['18 July 2025', '18 July 2025', '17 July 2025', '17 July 2025'],
    'city': ['Mumbai', 'pune', 'pune', 'Mumbai'],
    'temp': [34, 30, 20, 10]
}

df = pd.DataFrame(data)

In [ ]:
Series → One-dimensional
DataFrame → Two-dimensional

In [17]:
df = pd.DataFrame({'city': ['Mumbai', 'Pune'], 'temp': [34, 30]})

In [18]:
df

     city  temp
0  Mumbai    34
1    Pune    30

In [19]:
df.head()

     city  temp
0  Mumbai    34
1    Pune    30

In [20]:
df.tail(1)

   city  temp
1  Pune    30

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    2 non-null      object
 1   temp    2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [22]:
df.describe()

            temp
count   2.000000
mean   32.000000
std     2.828427
min    30.000000
25%    31.000000
50%    32.000000
75%    33.000000
max    34.000000

In [23]:
df

     city  temp
0  Mumbai    34
1    Pune    30

In [28]:
df.loc[0]['city']

'Mumbai'

In [29]:
df.loc[0]

city    Mumbai
temp        34
Name: 0, dtype: object

In [30]:
df.iloc[0]

city    Mumbai
temp        34
Name: 0, dtype: object

In [ ]:
loc
  1.  	Label-based indexing

iloc
  1. 	Integer position-based indexing

In [1]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Mumbai', 'Pune', 'Delhi'],
    'Temperature': [34, 30, 28]
}, index=[101, 102, 103])

print(df)

       City  Temperature
101  Mumbai           34
102    Pune           30
103   Delhi           28

In [6]:
df.loc[[101,102]]

       City  Temperature
101  Mumbai           34
102    Pune           30

In [34]:
df.iloc[0]

City           Mumbai
Temperature        34
Name: 101, dtype: object

In [37]:
df[df['Temperature'] > 30]

       City  Temperature
101  Mumbai           34

In [ ]:
Data Cleaning
*************
Handling missing data: df.fillna(), df.dropna()
Renaming columns:      df.rename()
Replacing values:      df.replace()

In [7]:
import pandas as pd

data = {
    'A': [1, 2, None, 4],
    'B': [None, 2, 3, 4]
}

df = pd.DataFrame(data)
print(df)

     A    B
0  1.0  NaN
1  2.0  2.0
2  NaN  3.0
3  4.0  4.0

In [8]:
df_filled = df.fillna(0)
print(df_filled)

     A    B
0  1.0  0.0
1  2.0  2.0
2  0.0  3.0
3  4.0  4.0

In [9]:
df_dropped = df.dropna()
print(df_dropped)

     A    B
1  2.0  2.0
3  4.0  4.0

In [10]:
df.columns

Index(['A', 'B'], dtype='object')

In [11]:
df = df.rename(columns={'A': 'AA'})

In [12]:
df

    AA    B
0  1.0  NaN
1  2.0  2.0
2  NaN  3.0
3  4.0  4.0

In [17]:
df_replaced = df.replace({1.0: '4.0', 30: 25})

In [18]:
df_replaced

    AA    B
0  4.0  NaN
1  2.0  2.0
2  NaN  3.0
3  4.0  4.0

In [ ]:
groupby()

pivot_table()

Aggregation functions: sum(), mean(), count()

In [49]:
import pandas as pd

data = {
    'City': ['Mumbai', 'Pune', 'Mumbai', 'Pune', 'Delhi'],
    'Temperature': [34, 30, 33, 31, 28],
    'Humidity': [80, 75, 82, 70, 65]
}

df = pd.DataFrame(data)
print(df)

     City  Temperature  Humidity
0  Mumbai           34        80
1    Pune           30        75
2  Mumbai           33        82
3    Pune           31        70
4   Delhi           28        65

In [58]:
df1 = df.groupby("City")["Temperature"].mean()

In [59]:
df1

City
Delhi     28.0
Mumbai    33.5
Pune      30.5
Name: Temperature, dtype: float64

In [61]:
df1 = df.groupby("City")["Temperature"].sum()

In [62]:
df1

City
Delhi     28
Mumbai    67
Pune      61
Name: Temperature, dtype: int64

In [2]:
# Pivot table
import pandas as pd

data = {
    'Date': ['2025-07-18', '2025-07-18', '2025-07-19', '2025-07-19', '2025-07-19'],
    'City': ['Mumbai', 'Pune', 'Mumbai', 'Pune', 'Delhi'],
    'Sales': [200, 150, 220, 180, 90]
}

df = pd.DataFrame(data)
print(df)

         Date    City  Sales
0  2025-07-18  Mumbai    200
1  2025-07-18    Pune    150
2  2025-07-19  Mumbai    220
3  2025-07-19    Pune    180
4  2025-07-19   Delhi     90

In [3]:
pivot_result = pd.pivot_table(df, values='Sales', index='Date',aggfunc='sum')
print(pivot_result)

            Sales
Date
2025-07-18    350
2025-07-19    490