In [ ]:
# Difference bet thread,multiprocess,assync

Thread :
   .  Multiple threads run within the same process
   .  Threads share the same memory space

    How it works
       Uses context switching
       GIL is mutex, Allows one thread is execute python bytecode at a time

   🔹 Best for
   ✅ I/O-bound tasks
      Network calls
      File read/write
      API calls
      Database queries

🔹 Advantages

✔ Low memory usage
✔ Faster context switching
✔ Easy communication (shared memory)

In [ ]:
import threading
def print_sentence(sentence):
    print(sentence)
sentences = [
    "Sentence 1: Hello!",
    "Sentence 2: Welcome to Python.",
    "Sentence 3: Multithreading is cool.",
    "Sentence 4: This is concurrent printing.",
    "Sentence 5: All printed at once!"
]
threads = []
for s in sentences:
    t = threading.Thread(target=print_sentence, args=(s,))
    threads.append(t)
    t.start()

for t in threads:
    t.join()

In [ ]:
2️⃣ Multiprocessing

   Multiple processes, each with its own memory space
   No GIL limitation → true parallelism

🔹 How it works

OS schedules processes on multiple CPU cores

🔹 Best for
✅ CPU-bound tasks
Data processing
Image/video processing
Machine learning
Heavy calculations

Advantages
✔ True parallel execution
✔ Fully utilizes multi-core CPUs
✔ No GIL issue

In [ ]:
An event loop is a core mechanism used in asynchronous, 
non-blocking programming to handle multiple tasks efficiently using a single thread.

Coroutines are special functions that can pause and resume execution, 
allowing multiple tasks to run concurrently on a single thread, usually managed by an event loop

In [ ]:
3️⃣ Async / Asynchronous Programming
🔹 What is it?

Single-threaded, non-blocking execution
Uses event loop and coroutines
Based on async/await

🔹 How it works

While waiting for I/O, control switches to another task
No parallel execution, but high concurrency

🔹 Best for

✅ High-concurrency I/O-bound tasks

Web servers (FastAPI, Node.js)
Microservices
Web scraping
Chat applications

In [ ]:
import asyncio

async def solve():
    print("How are you")

async def solve1():
    print("I am fine")

async def solve2():
    print("I am good")

async def main():
    await asyncio.gather(solve(), solve1(), solve2())

#asyncio.run(main())
await main()

In [ ]:
⭐ How do we handle this failure?

1️⃣ Circuit Breaker Pattern

        Stops calling the failed service
        Returns fallback response
        Prevents system collapse

2️⃣ Retry + Backoff (Exponential)
3️⃣ Time-outs
4️⃣ Bulkheads
5️⃣ Fallback Logic
6️⃣ Event-driven architecture
     ⭐ Why Event-Driven Architecture?
     ✔ 1. Loose Coupling
            Services don’t directly call each other.
            If Payment is down, Order still works.
     ✔ 2. High Scalability
            Events can be processed in parallel by many consumers.
     ✔  3. Better Performance
        No waiting for synchronous API calls.
        Low latency + fast responses.
    ✔ 4. High Fault Tolerance
    
    Because everything is async, failure of one service doesn’t block others.
                
7️⃣ Saga Pattern

    The Saga Pattern is used in microservices to manage distributed transactions without using distributed locks or 2-phase commit (2PC).

Saga ensures:
    Data consistency
    Across multiple microservices
    Using a series of local transactions
    With compensating actions (undo steps)

No centralized transaction manager.
No global locks.
Highly scalable.
****************
8️⃣ Outbox Pattern
    It solves the problem of data inconsistency and missing events.
        
When a service performs 2 actions:

1️⃣ Save data in database
2️⃣ Publish event to Kafka

These are two different systems, so:

DB commit succeeds

Kafka publish fails ❌
➡ Order is created but no event goes to Inventory Service
➡ Inventory will NOT reduce stock

Or vice-versa:

Event published

DB save fails ❌
➡ Inventory reduces stock but order not created

This is a classic distributed transaction problem.

    The Outbox Pattern ensures that events are never lost.

In [ ]:
| Feature             | **Gunicorn**                | **Uvicorn**                     |
| ------------------- | --------------------------- | ------------------------------- |
| Type                | **WSGI server**             | **ASGI server**                 |
| Works with          | Django (traditional), Flask | FastAPI, Starlette, Django ASGI |
| Supports Async      | ❌ No                        | ✔️ Yes                          |
| Supports WebSockets | ❌ No                        | ✔️ Yes                          |
| Protocol            | HTTP 1.1                    | HTTP 1.1 + HTTP/2 + WebSockets  |
| Best for            | Sync apps                   | Async apps                      |
| Worker Types        | Multiple worker classes     | Async workers                   |
| Performance         | Good                        | Extremely fast                  |
| Architecture        | Prefork model               | Async event-loop                |

In [ ]:
asyncio:-
  1. A module (library) in Python
  2. Provides tools to run asynchronous code
  3. asyncio.run(main())	

await:-
  1.  A keyword in Python
  2.  Tells Python to pause and wait

In [ ]:
| Feature       | Threads           | Multiprocessing    | Asyncio                     |
| ------------- | ----------------- | ------------------ | --------------------------- |
| Runs in       | Same process      | Separate processes | Same process                |
| Parallel?     | ❌ No (GIL blocks) | ✅ Yes              | ❌ No                        |
| For CPU-bound | Bad               | Best               | Bad                         |
| For I/O-bound | Good              | Overkill           | Best                        |
| Memory        | Shared            | Separate           | Shared                      |
| Switch type   | Preemptive (OS)   | Preemptive (OS)    | Cooperative (`await`)       |
| Overhead      | Low               | High               | Very low                    |
| Typical use   | I/O tasks         | Heavy CPU tasks    | High concurrency networking |

In [ ]:
Global Interpreter Lock (GIL): 

The GIL is a mutex that allows only one thread to execute Python code at a time.

In [ ]:
To retrieve data efficiently from a large dataset,

  ✅ 1. Use Indexing

                CREATE INDEX idx_users_email ON users(email);
  ✅ 2. Use Pagination
  ✅ 3. Use Caching (Redis, Memcache)
  ✅ 4. Retrieve Only Required Columns
  ✅ 5. Use Proper Data Types
  ✅ 7. Use Partitioning
  ✅ 8. Use Materialized Views
  ✅ 9. Avoid N+1 Queries

     Use “select_related”, “prefetch_related” in Django.
  ✅ 10. Use Query Optimization Tools
      EXPLAIN SELECT * FROM users WHERE email='abc@example.com';

In [ ]:
Program : -

A program is a sequence of instructions written in programming language

Process : -

A process is simple an instance of a program that is being executed.

In [ ]:
#  How Python Manages Memory

Python handles memory automatically

  1️⃣ Python Memory Architecture
        Python memory is divided into two main parts:

        🔹 1. Stack Memory
                Stores function calls
                Stores local variables & references
                Managed automatically

                def add():
                    x = 10
                    y = 20
                    ➡ x and y references are stored in stack

            🔹 2. Heap Memory
                 Stores objects
                 Managed by Python’s Memory Manager
 2️⃣ Reference Counting
    Each object keeps a reference count.
            a = []
            b = a
            c = a
     Reference count = 3
     When count becomes 0, memory is released.
         
 3️⃣ Garbage Collection (GC)
     Used to handle circular references.

In [17]:
import pandas as pd

events = [
    {'user_id': 1, 'channel_id': 101, 'change_time': 5},
    {'user_id': 1, 'channel_id': 103, 'change_time': 30},
    {'user_id': 1, 'channel_id': 101, 'change_time': 60},
    {'user_id': 2, 'channel_id': 102, 'change_time': 15},
    {'user_id': 2, 'channel_id': 102, 'change_time': 45},
    {'user_id': 2, 'channel_id': 104, 'change_time': 25},    
    {'user_id': 1, 'channel_id': 102, 'change_time': 10}
]

df = pd.DataFrame(events)

In [18]:
df

   user_id  channel_id  change_time
0        1         101            5
1        1         103           30
2        1         101           60
3        2         102           15
4        2         102           45
5        2         104           25
6        1         102           10

In [19]:
df = df.sort_values(by=['user_id','change_time'])

In [20]:
df

   user_id  channel_id  change_time
0        1         101            5
6        1         102           10
1        1         103           30
2        1         101           60
3        2         102           15
5        2         104           25
4        2         102           45

In [21]:
df['next_time'] = df.groupby('user_id')['change_time'].shift(-1)

In [22]:
df

   user_id  channel_id  change_time  next_time
0        1         101            5       10.0
6        1         102           10       30.0
1        1         103           30       60.0
2        1         101           60        NaN
3        2         102           15       25.0
5        2         104           25       45.0
4        2         102           45        NaN

In [23]:
df['duration'] = df['next_time'] - df['change_time']

In [24]:
df

   user_id  channel_id  change_time  next_time  duration
0        1         101            5       10.0       5.0
6        1         102           10       30.0      20.0
1        1         103           30       60.0      30.0
2        1         101           60        NaN       NaN
3        2         102           15       25.0      10.0
5        2         104           25       45.0      20.0
4        2         102           45        NaN       NaN

In [25]:
df  = df.dropna(subset=['duration'])

In [26]:
df

   user_id  channel_id  change_time  next_time  duration
0        1         101            5       10.0       5.0
6        1         102           10       30.0      20.0
1        1         103           30       60.0      30.0
3        2         102           15       25.0      10.0
5        2         104           25       45.0      20.0

In [29]:
df  = df.groupby(['user_id','channel_id']).sum().reset_index()

In [30]:
df

   user_id  channel_id  change_time  next_time  duration
0        1         101            5       10.0       5.0
1        1         102           10       30.0      20.0
2        1         103           30       60.0      30.0
3        2         102           15       25.0      10.0
4        2         104           25       45.0      20.0

In [36]:

result = df.to_dict(orient="records")
print(result)

[{'user_id': 1, 'channel_id': 101, 'change_time': 5, 'next_time': 10.0, 'duration': 5.0}, {'user_id': 1, 'channel_id': 102, 'change_time': 10, 'next_time': 30.0, 'duration': 20.0}, {'user_id': 1, 'channel_id': 103, 'change_time': 30, 'next_time': 60.0, 'duration': 30.0}, {'user_id': 2, 'channel_id': 102, 'change_time': 15, 'next_time': 25.0, 'duration': 10.0}, {'user_id': 2, 'channel_id': 104, 'change_time': 25, 'next_time': 45.0, 'duration': 20.0}]

In [45]:
from collections import defaultdict

def solve(events):
    s = defaultdict(int)
    for k in events:
        key = (k['user_id'], k['channel_id'])
        s[key] += k['change_time']
    print(s)
events = [
    {'user_id': 1, 'channel_id': 101, 'change_time': 5},
    {'user_id': 1, 'channel_id': 103, 'change_time': 30},
    {'user_id': 1, 'channel_id': 101, 'change_time': 60},
    {'user_id': 2, 'channel_id': 102, 'change_time': 15},
    {'user_id': 2, 'channel_id': 102, 'change_time': 45},
    {'user_id': 2, 'channel_id': 104, 'change_time': 25},    
    {'user_id': 1, 'channel_id': 102, 'change_time': 10}
]

res = solve(events)

defaultdict(<class 'int'>, {(1, 101): 65, (1, 103): 30, (2, 102): 60, (2, 104): 25, (1, 102): 10})