In [ ]:
annotations

In [ ]:
In Django, F() expressions are used to refer to model field values directly 
in the database

from django.db.models import F

# Increment the price of all books by 10
Book.objects.update(price=F('price') + 10)

In [ ]:
In Django, annotations are a powerful feature
provided by the Django ORM (Object-Relational Mapping)
to add calculated fields to querysets. This allows you to add
additional fields to the output of a query, based on the existing 
fields in the model, without modifying the actual model or database schema.

Here's a detailed overview of how to use annotations in Django:

In [ ]:
from django.db.models import F

# Adding a discount price
books = Book.objects.annotate(discounted_price=F('price') * 0.9)
for book in books:
    print(f"{book.title} - Discounted Price: {book.discounted_price}")

In [ ]:
a = [-12,12,0,342,-1242,123,-675,564]

In [1]:
def solve(a):
    for i in range(len(a)):
        for j in range(i+1,len(a)):
            if a[i] > a[j]:
                a[i],a[j] = a[j],a[i]
    return a



a = [-12,12,0,342,-1242,123,-675,564]
result = solve(a)
print(a)

[-1242, -675, -12, 0, 12, 123, 342, 564]

In [4]:
def solve(s):
    res = ""
    len_str = len(s)-1
    for i in range(len_str,-1,-1):
        res = res+s[i]
    print(res)

s= "HelloWorld!"
result = solve(s)

!dlroWolleH

In [7]:
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math':   [85, 90, 75, 80],
    'Science': [88, 85, 90, 82],
    'English': [82, 88, 85, 90]
}

In [5]:
import numpy as np
import pandas as pd

In [8]:
df = pd.DataFrame(data)

In [16]:
def calculate_percentage(data):
    print(data['Math'])

In [15]:
df

   Student  Math  Science  English percentage
0    Alice    85       88       82        NaN
1      Bob    90       85       88        NaN
2  Charlie    75       90       85        NaN
3    David    80       82       90        NaN

In [42]:
df['sum'] = df['Math']+df['Science']+df['English']

In [47]:
df['percentage'] = df['sum'] / 300 * 100

In [48]:
df

   Student  Math  Science  English  percentage  sum
0    Alice    85       88       82   85.000000  255
1      Bob    90       85       88   87.666667  263
2  Charlie    75       90       85   83.333333  250
3    David    80       82       90   84.000000  252

In [ ]:
create a numpy array 1 to 10 and filter out the even numbers

In [55]:
arr = np.arange(1,11)

In [58]:
for i in arr:
    if i % 2 == 0:
        print(i,end=" ")

2 4 6 8 10

In [68]:
names = pd.Series(['Alice', 'Bob', 'Charlie', 'David'])
grades = pd.Series([85, 90, 75, 80])

In [83]:
df = pd.DataFrame({"name":names,"grade":grades})

In [84]:
df

      name  grade
0    Alice     85
1      Bob     90
2  Charlie     75
3    David     80

In [5]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Function to apply
def custom_function(row):
    #print(row['A'], row['B'], row['C'])
    return row['A'] + row['B'] * row['C']

# Apply the function row-wise
df['Result'] = df.apply(lambda row: custom_function(row), axis=1)

print(df)

1 4 7
2 5 8
3 6 9
   A  B  C  Result
0  1  4  7      29
1  2  5  8      42
2  3  6  9      57

In [11]:
import pandas as pd

# Sample data
names = pd.Series(['Alice', 'Bob', 'Charlie', 'David'])
grades = pd.Series([85, 90, 75, 80])

# Combine into a DataFrame
df = pd.DataFrame({'Name': names, 'Grade': grades})

# Sort the DataFrame by the 'Grade' column
df_sorted = df.sort_values(by='Grade')

# Extract the sorted names
sorted_names = df_sorted[['Name','Grade']].reset_index(drop=True)

print(sorted_names)

      Name  Grade
0  Charlie     75
1    David     80
2    Alice     85
3      Bob     90