In [17]:
import requests
def solve(city):
    page = 1
    rating = 0
    output = []
    while True:
        url = f"https://jsonmock.hackerrank.com/api/food_outlets?city={city}&page={page}"
        data = requests.get(url).json()
        for k in data['data']:
            if rating < k['user_rating']['average_rating']:
                rating = k['user_rating']['average_rating']
                output = [k['name']]
            elif rating == k['user_rating']['average_rating']:
                output.append(k['name'])

        page += 1
        if page > data['total_pages']:
            break
    return output
res = solve("Denver")
print(res)

['Sushi Kashiba', 'Peninsula Grand Hotel', 'Plum by Bent Chair', "R' ADDA", 'Palladium Social']

In [4]:
# Return the restaurant name(s) with the lowest average rating for a given city.

import requests
def solve(city):
    page = 1
    rating = float('inf')
    output = []
    while True:
        url = f"https://jsonmock.hackerrank.com/api/food_outlets?city={city}&page={page}"
        data = requests.get(url).json()
        for k in data['data']:
            if rating > k['user_rating']['average_rating']:
                rating = k['user_rating']['average_rating']
                output = [k['name']]
            elif rating == k['user_rating']['average_rating']:
                output.append(k['name'])
        page += 1
        if page > data['total_pages']:
            break
    return output
res = solve("Denver")
print(res)

["Grandmama's Cafe", 'Eat Play Love', 'Cafe Safar', 'MRP - My Regular Place']

In [5]:
def solve(city):
    


res = solve("Denver")
print(res)

None

In [ ]:
What is a Lambda Layer (AWS)?

An AWS Lambda Layer is a shared, reusable package that contains libraries, 
dependencies, or custom runtime code which can be used by multiple AWS Lambda functions.

Think of it as a dependency layer that sits outside your Lambda function code.
    
Step 2: Upload as Lambda Layer

AWS Console → Lambda → Layers → Create layer
Upload requests_layer.zip
Select compatible runtime (e.g., Python 3.10)

In [ ]:
Deploy
  ↓
Invoke
  ↓
Cold Start?
  ├── Yes → Init → Execute → Freeze
  └── No  → Execute → Freeze
          ↓
        Warm Start
          ↓
      Terminate (eventually)

In [ ]:
A cold start happens when AWS Lambda creates a brand-new execution environment 
to run your function for the first time or after being idle

What happens during a Cold Start?

When a cold start occurs, AWS does the following:

    Creates a new container
    Loads the runtime (Python / Node / Java)
    Mounts Lambda Layers (/opt)
    Loads your function code (/var/task)
    Executes global code (outside the handler)
    Calls the handler function

In [ ]:
A warm start happens when AWS Lambda reuses an existing execution environment (container)
to handle a new request after a previous invocation.

Because everything is already initialized, the function runs much faster.

What happens during a Warm Start?

During a warm start:

No new container is created
Runtime is already loaded
Layers are already mounted
Global code is NOT re-executed

Only the handler function runs

⚡ Result: Low latency

In [ ]:
Decorator Design pattern:-

The Decorator Design Pattern lets you add new behavior to an object dynamically without modifying its existing code.

1️⃣ When should you use Decorator Pattern?

Use it when:

You want to add responsibilities at runtime

In [18]:
# 4️⃣ Step-by-Step Implementation
# Step 1: Component Interface

from abc import ABC, abstractmethod

class Notifier(ABC):
    @abstractmethod
    def send(self, message: str):
        pass

In [20]:
# Step 2: Concrete Component
class EmailNotifier(Notifier):
    def send(self, message: str):
        print(f"Email sent: {message}")

In [21]:
# Step 3: Base Decorator

class NotifierDecorator(Notifier):
    def __init__(self, notifier: Notifier):
        self._notifier = notifier

    def send(self, message: str):
        self._notifier.send(message)

In [22]:
# Step 4: Concrete Decorators
# SMS Decorator
class SMSNotifier(NotifierDecorator):
    def send(self, message: str):
        super().send(message)
        print(f"SMS sent: {message}")

In [23]:
notifier = EmailNotifier()
notifier = SMSNotifier(notifier)
# notifier = SlackNotifier(notifier)

notifier.send("Server is down!")

Email sent: Server is down!
SMS sent: Server is down!

In [ ]:
Why does a list store duplicate data?
   1️⃣ Lists represent sequences
   2️⃣ Lists are index-based

In [ ]:
Why does a set store only unique values in Python?

In Python, a set stores unique values by design because it is implemented using a hash table,
and each element is identified by its hash value + equality check.

In [ ]:
Pods in the same namespace normally communicate by default. If they cannot,
the most common reason is a NetworkPolicy restricting traffic. Other causes include CNI plugin issues,
service selector mismatch, DNS problems, or pod readiness failures.

In [ ]:
1️⃣ Pods are in Pending state. What could be the reason?
    ✅ Answer:
    
    Insufficient CPU or memory on nodes
    Resource requests are too high
    NodeSelector / Taints & Tolerations mismatch
    PVC not bound
    
    Cluster Autoscaler not adding nodes

In [ ]:
Types of Indexes in MySQL

Types of Indexes in MySQL

1. Primary Key index
2. Clustered Index (InnoDB)
   
   Table data is physically stored in index order
   Primary key is the clustered index
   Only one clustered index per table

In [ ]:
| Method | Access Type     | Speed  |
| ------ | --------------- | ------ |
| `loc`  | Label-based     | Medium |
| `iloc` | Position-based  | Medium |
| `at`   | Single label    | Fast   |
| `iat`  | Single position | Fast   |

In [ ]:
| Function   | Use Case                           |
| ---------- | ---------------------------------- |
| `merge()`  | SQL-style joins                    |
| `join()`   | Index-based join                   |
| `concat()` | Stack data vertically/horizontally |

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "emp_id": [1, 2, 3],
    "name": ["Umesh", "Ravi", "Amit"]
})

df2 = pd.DataFrame({
    "emp_id": [1, 2, 4],
    "salary": [50000, 60000, 70000]
})

result = pd.merge(df1, df2, on="emp_id", how="inner")
print(result)

   emp_id   name  salary
0       1  Umesh   50000
1       2   Ravi   60000

In [2]:
df1

   emp_id   name
0       1  Umesh
1       2   Ravi
2       3   Amit

In [3]:
df2

   emp_id  salary
0       1   50000
1       2   60000
2       4   70000

In [4]:
df = df1.merge(df2,on='emp_id',how='inner')

In [5]:
df

   emp_id   name  salary
0       1  Umesh   50000
1       2   Ravi   60000

In [ ]:
2️⃣ join() – Index-based join

In [6]:
df1 = pd.DataFrame({
    "name": ["Umesh", "Ravi", "Amit"]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "salary": [50000, 60000]
}, index=[1, 2])

result = df1.join(df2)
print(result)

    name   salary
1  Umesh  50000.0
2   Ravi  60000.0
3   Amit      NaN

In [7]:
df1

    name
1  Umesh
2   Ravi
3   Amit

In [8]:
df2

   salary
1   50000
2   60000

In [9]:
result = df1.join(df2)
print(result)

    name   salary
1  Umesh  50000.0
2   Ravi  60000.0
3   Amit      NaN

In [10]:
result

    name   salary
1  Umesh  50000.0
2   Ravi  60000.0
3   Amit      NaN

In [ ]:
df1 = pd.DataFrame({"name": ["Umesh", "Ravi"]})
df2 = pd.DataFrame({"salary": [50000, 60000]})

result = pd.concat([df1, df2], axis=1)

In [ ]:
7️⃣ How does Pandas handle missing values?

df.isna()
df.fillna(0)
df.dropna()

In [ ]:
pd.read_csv('file.csv', chunksize=100000)

In [ ]:
copy() → independent memory

view() → shared memory

In [ ]:
🧩 Scenario 3: Find the difference between current and previous employee salary

SELECT emp_name, salary,
       LAG(salary) OVER (ORDER BY salary) AS prev_salary,
       salary - LAG(salary) OVER (ORDER BY salary) AS diff
FROM employees;

| emp_name | salary | prev_salary | diff |
| -------- | ------ | ----------- | ---- |
| John     | 5000   | NULL        | NULL |
| David    | 5500   | 5000        | 500  |
| Mary     | 6000   | 5500        | 500  |
| Lisa     | 6500   | 6000        | 500  |
| Tom      | 7000   | 6500        | 500  |