In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
        "Name" : ["u","k","s"],
        "Makrs" : [60,40,43]

}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  Name  Makrs
0    u     60
1    k     40
2    s     43

In [8]:
def calculate_result(marks):
    if marks > 55:
        return "PASS"
    else:
        return "FAIL"

In [9]:
df['result'] = df['Makrs'].apply(calculate_result)

In [10]:
df

  Name  Makrs result
0    u     60   PASS
1    k     40   FAIL
2    s     43   FAIL

In [3]:
li = [1,2,'a']
try:
    for i in li:
        print(1/i)
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)
finally:
    print("Hello how are you")

1.0
0.5
unsupported operand type(s) for /: 'int' and 'str'
Hello how are you

In [ ]:
li = [1, 0, 'a']
try:
    for i in li:
        print("output", 1 / i)
except ZeroDivisionError as e:
    print("ZeroDivisionError:", e)
except TypeError as e:
    print("TypeError:", e)

In [1]:
def solve(s,n):
    for i in range(len(s)):
        for j in range(i,len(s)):
            if s[i] < s[j]:
                s[i],s[j] = s[j],s[i]
    return s[n-1]

s = [-1,3,4.6,4,7]
n = 2
result = solve(s,n)
print(result)

4.6

In [ ]:
def solve(li):
    sum = 0
    for i in li:
        if isinstance(i,list) == True:
            return sum + solve(i)
        else:
            sum += i
    return sum

In [2]:
import pandas as pd
import numpy as np

[8, 9]

Merged DataFrame (inner join):
   ID     Name  Score
0   3  Charlie     85
1   4    David     90

Concatenated DataFrame (along rows):
   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eve
5   6    Frank